#!/bin/sh
set -e

WP_DIR="/var/www/html"
WP_CONFIG="$WP_DIR/wp-config.php"
EXTRA_SRC="/usr/src/wordpress/config-extra.php"
EXTRA_DEST="$WP_DIR/config-extra.php"

# Ensure config-extra.php always exists in /var/www/html
if [ -f "$EXTRA_SRC" ]; then
    cp "$EXTRA_SRC" "$EXTRA_DEST"
fi

# Patch wp-config.php if needed
if [ -f "$WP_CONFIG" ]; then
    if ! grep -q "config-extra.php" "$WP_CONFIG"; then
        echo "Patching wp-config.php..."
        sed -i "/\/\* That's all, stop editing! Happy publishing. \*\//i \
if ( file_exists( __DIR__ . '/config-extra.php' ) ) {\n\
    require __DIR__ . '/config-extra.php';\n\
}\n" "$WP_CONFIG"
    else
        echo "wp-config.php already patched."
    fi
else
    echo "wp-config.php not found (on first run). Will be generated by WP."
fi
